### ISSUE TITLE
Exception in thread "main" java.lang.NullPPointerException

### ISSUE THREAD

**Issue by murpholinox** [GarmanGroup/RADDOSE-3D#1] opened 2016-10-11 18:18 UTC
Brand new ubuntu 16.04

fmp@eva01:~/Bins$ java -jar raddose3d.jar -i burn_f3.6_nat.inp
Load File: burn_f3.6_nat.inp
No output specifications given. Using defaults.
Cell volume: 231192.00 Angstroms cubed.
Exception in thread "main" java.lang.NullPointerException
    at se.raddo.raddose3D.CoefCalcCompute.addSolventConcentrations(CoefCalcCompute.java:455)
    at se.raddo.raddose3D.CoefCalcFromParams.calculateAtomOccurrences(CoefCalcFromParams.java:111)
    at se.raddo.raddose3D.CoefCalcFromParams.<init>(CoefCalcFromParams.java:64)
    at se.raddo.raddose3D.parser.InputfileParser.crystal(InputfileParser.java:342)
    at se.raddo.raddose3D.parser.InputfileParser.configfile(InputfileParser.java:191)
    at se.raddo.raddose3D.InputParser.sendData(InputParser.java:78)
    at se.raddo.raddose3D.Experiment.process(Experiment.java:39)
    at se.raddo.raddose3D.RD3D.runExperiment(RD3D.java:98)
    at se.raddo.raddose3D.RD3D.main(RD3D.java:66)
fmp@eva01:~/Bins$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Here is the input

```
Crystal

Type cuboid
Dimensions 200 200 100
CoefCalc RDV3
UnitCell 78 78 38 90 90 90
NumMonomers 8
NumResidues 129
ProteinHeavyAtoms S 10
SolventFraction .39


Beam

Type Gaussian
FWHM 250 50
Flux 3.6e10
Energy 13.19
Collimation Rectangular 200 200


Wedge 1 100
ExposureTime 600


```

**Comment by murpholinox** [comment] 2016-10-11 18:42
Same error shows with java (8) from oracle.
Same error shows with raddose3d.jar v 1.2.427 or v 1.2.415

**Comment by JonnyCBB** [comment] 2016-10-11 19:19
Hey,

I'm a bit busy at the moment so I'll try to get to this a little later if this quick fix doesn't work. I think this is an issue that we've fixed with [this line here](https://github.com/GarmanGroup/RADDOSE-3D/blob/master/src/se/raddo/raddose3D/CoefCalcFromParams.java#L119) but we haven't yet put in an official release yet (we're hoping to get a significant release within the next month or two).

Basically I think the problem is that without that `if statement` RADDOSE-3D is expecting you to have an additional line in the input file specifying the solvent content.
add the following line to the `Crystal` block:

```
SOLVENTHEAVYCONC S 0
```

Let me know if that solves the problem.

Additionally if you run with `CoefCalc RDV3` as you have, make sure that the `constants` folder is in the working directory.

Fingers crossed

**Comment by murpholinox** [comment] 2016-10-11 19:36
Thanks a lot. Adding the line solves the problem.

**Comment by JonnyCBB** [comment] 2016-10-11 21:27
Glad to hear it. This will be fixed in the next release :)

**Closed as completed by JonnyCBB** 2016-10-11 21:27 UTC
